git:
  depth: 1
branches:
  except:
    - /(?i:appveyor)/
sudo: false  # docker VM
matrix:
  include:
  - os: linux
    env: HOST="" API="alsa"
    compiler: gcc
  - os: linux
    env: HOST="" API="alsa"
    compiler: clang
  - os: linux
    env: HOST="" API="jack"
    compiler: gcc
  - os: linux
    env: HOST="" API="jack"
    compiler: clang
  - os: linux
    env: HOST="--with-jack" API="alsa"
    compiler: gcc
  - os: linux
    env: HOST="--with-jack" API="alsa"
    compiler: clang
  # - os: linux
  #   env: HOST="--host=i686-w64-mingw32" API="winmm"
  #  compiler: gcc
  # - os: linux
  #  env: HOST="--host=x86_64-w64-mingw32" API="winmm"
  #  compiler: gcc
  # jack and asound not found on ARM gnueabihf
  # - os: linux
  #   env: HOST="--host=arm-linux-gnueabihf" API="alsa"
  #   compiler: gcc
  # - os: linux
  #   env: HOST="--host=arm-linux-gnueabihf" API="jack"
  #   compiler: gcc
  - os: osx
    env: HOST="" API="coremidi"
    compiler: gcc
  - os: osx
    env: HOST="" API="coremidi"
    compiler: clang
  - os: osx
    env: HOST="" API="jack"
    compiler: gcc
  - os: osx
    env: HOST="" API="jack"
    compiler: clang
  - os: osx
    env: HOST="--with-jack" API="coremidi"
    compiler: gcc
  - os: osx
    env: HOST="--with-jack" API="coremidi"
    compiler: clang
language: c++
group: travis_latest


addons:
  apt:
    packages:
    - autoconf
    - libtool
    - autopoint
    - automake
    - libasound-dev
    - libjack-dev
    - libcppunit-dev
    - doxygen
    - g++-mingw-w64-i686
    - g++-mingw-w64-x86-64
    - g++-arm-linux-gnueabihf


before_install:
    - eval "${MATRIX_EVAL}"
    - if test "$TRAVIS_OS_NAME" = osx ; then  brew update ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then if brew upgrade boost ; then echo "upgraded" ; else echo "nothing to be done"; fi ;  fi
    - if test "$TRAVIS_OS_NAME" = osx ; then rm -rf /usr/local/include/c++ ; fi # fix broken gcc installation
    - if test "$TRAVIS_OS_NAME" = osx ; then brew install $EXTRA_BREW  gettext flex bison libtool autoconf jack   doxygen ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then brew link --force $EXTRA_BREW gettext flex bison libtool autoconf jack ; fi
    - mkdir -p config
    - touch config/config.rpath

script:
    - mkdir -p config
    - touch config/config.rpath
    - ./autogen.sh --disable-apisearch --with-$API $HOST && make && make -j4 && $TEST_RUNNER make check || (cat test-suite.log ; false)
    - make distcheck
    - cat tests/errors.log
